# frozen_string_literal: true

module PayabliSdk
  module Types
    class QueryPayoutTransactionRecordsItem < Internal::Types::Model
      field :batch_number, -> { String }, optional: true, nullable: false, api_name: "BatchNumber"
      field :batch_id, -> { Integer }, optional: true, nullable: false, api_name: "BatchId"
      field :bills, -> { Internal::Types::Array[PayabliSdk::Types::BillPayOutData] }, optional: true, nullable: false, api_name: "Bills"
      field :card_token, -> { String }, optional: true, nullable: false, api_name: "CardToken"
      field :check_data, -> { PayabliSdk::Types::FileContent }, optional: true, nullable: false, api_name: "CheckData"
      field :check_number, -> { String }, optional: true, nullable: false, api_name: "CheckNumber"
      field :comments, -> { String }, optional: true, nullable: false, api_name: "Comments"
      field :created_at, -> { String }, optional: true, nullable: false, api_name: "CreatedAt"
      field :entry_name, -> { String }, optional: true, nullable: false, api_name: "EntryName"
      field :events, -> { Internal::Types::Array[PayabliSdk::Types::QueryTransactionEvents] }, optional: true, nullable: false, api_name: "Events"
      field :external_paypoint_id, -> { String }, optional: true, nullable: false, api_name: "externalPaypointID"
      field :fee_amount, -> { Integer }, optional: true, nullable: false, api_name: "FeeAmount"
      field :gateway, -> { String }, optional: true, nullable: false, api_name: "Gateway"
      field :has_vcard_transactions, -> { Internal::Types::Boolean }, optional: true, nullable: false, api_name: "HasVcardTransactions"
      field :id_out, -> { Integer }, optional: true, nullable: false, api_name: "IdOut"
      field :is_same_day_ach, -> { Internal::Types::Boolean }, optional: true, nullable: false, api_name: "IsSameDayACH"
      field :last_updated, -> { String }, optional: true, nullable: false, api_name: "LastUpdated"
      field :net_amount, -> { Integer }, optional: true, nullable: false, api_name: "NetAmount"
      field :parent_org_name, -> { String }, optional: true, nullable: false, api_name: "ParentOrgName"
      field :parent_org_id, -> { Integer }, optional: true, nullable: false, api_name: "ParentOrgId"
      field :payment_data, -> { PayabliSdk::Types::QueryPayoutTransactionRecordsItemPaymentData }, optional: true, nullable: false, api_name: "PaymentData"
      field :payment_id, -> { String }, optional: true, nullable: false, api_name: "PaymentId"
      field :payment_method, -> { String }, optional: true, nullable: false, api_name: "PaymentMethod"
      field :payment_status, -> { String }, optional: true, nullable: false, api_name: "PaymentStatus"
      field :payout_program, -> { String }, optional: true, nullable: false, api_name: "PayoutProgram"
      field :paypoint_dbaname, -> { String }, optional: true, nullable: false, api_name: "PaypointDbaname"
      field :paypoint_legalname, -> { String }, optional: true, nullable: false, api_name: "PaypointLegalname"
      field :risk_action, -> { String }, optional: true, nullable: false, api_name: "RiskAction"
      field :risk_action_code, -> { Integer }, optional: true, nullable: false, api_name: "RiskActionCode"
      field :risk_flagged, -> { Internal::Types::Boolean }, optional: true, nullable: false, api_name: "RiskFlagged"
      field :risk_flagged_on, -> { String }, optional: true, nullable: false, api_name: "RiskFlaggedOn"
      field :risk_reason, -> { String }, optional: true, nullable: false, api_name: "RiskReason"
      field :risk_status, -> { String }, optional: true, nullable: false, api_name: "RiskStatus"
      field :schedule_id, -> { Integer }, optional: true, nullable: false, api_name: "ScheduleId"
      field :settlement_status, -> { String }, optional: true, nullable: false, api_name: "SettlementStatus"
      field :source, -> { String }, optional: true, nullable: false, api_name: "Source"
      field :status, -> { Integer }, optional: true, nullable: false, api_name: "Status"
      field :total_amount, -> { Integer }, optional: true, nullable: false, api_name: "TotalAmount"
      field :vendor, -> { PayabliSdk::Types::VendorQueryRecord }, optional: true, nullable: false, api_name: "Vendor"
    end
  end
end
