# frozen_string_literal: true

module PayabliSdk
  module Types
    class QueryBatchesOutResponseRecordsItem < Internal::Types::Model
      field :ach_amount, -> { Integer }, optional: true, nullable: false, api_name: "AchAmount"
      field :ach_records, -> { Integer }, optional: true, nullable: false, api_name: "AchRecords"
      field :ach_status, -> { Integer }, optional: true, nullable: false, api_name: "AchStatus"
      field :ach_status_text, -> { String }, optional: true, nullable: false, api_name: "AchStatusText"
      field :batch_amount, -> { Integer }, optional: true, nullable: false, api_name: "BatchAmount"
      field :batch_cancelled_amount, -> { Integer }, optional: true, nullable: false, api_name: "BatchCancelledAmount"
      field :batch_cancelled_records, -> { Integer }, optional: true, nullable: false, api_name: "BatchCancelledRecords"
      field :batch_date, -> { String }, optional: true, nullable: false, api_name: "BatchDate"
      field :batch_number, -> { String }, optional: true, nullable: false, api_name: "BatchNumber"
      field :batch_paid_amount, -> { Integer }, optional: true, nullable: false, api_name: "BatchPaidAmount"
      field :batch_paid_records, -> { Integer }, optional: true, nullable: false, api_name: "BatchPaidRecords"
      field :batch_processed_amount, -> { Integer }, optional: true, nullable: false, api_name: "BatchProcessedAmount"
      field :batch_processed_records, -> { Integer }, optional: true, nullable: false, api_name: "BatchProcessedRecords"
      field :batch_processing_amount, -> { Integer }, optional: true, nullable: false, api_name: "BatchProcessingAmount"
      field :batch_processing_records, -> { Integer }, optional: true, nullable: false, api_name: "BatchProcessingRecords"
      field :batch_records, -> { Integer }, optional: true, nullable: false, api_name: "BatchRecords"
      field :batch_status, -> { Integer }, optional: true, nullable: false, api_name: "BatchStatus"
      field :batch_status_text, -> { String }, optional: true, nullable: false, api_name: "BatchStatusText"
      field :card_amount, -> { Integer }, optional: true, nullable: false, api_name: "CardAmount"
      field :card_records, -> { Integer }, optional: true, nullable: false, api_name: "CardRecords"
      field :card_status, -> { Integer }, optional: true, nullable: false, api_name: "CardStatus"
      field :card_status_text, -> { String }, optional: true, nullable: false, api_name: "CardStatusText"
      field :check_amount, -> { Integer }, optional: true, nullable: false, api_name: "CheckAmount"
      field :check_records, -> { Integer }, optional: true, nullable: false, api_name: "CheckRecords"
      field :check_status, -> { Integer }, optional: true, nullable: false, api_name: "CheckStatus"
      field :check_status_text, -> { String }, optional: true, nullable: false, api_name: "CheckStatusText"
      field :entry_name, -> { String }, optional: true, nullable: false, api_name: "EntryName"
      field :external_paypoint_id, -> { String }, optional: true, nullable: false, api_name: "externalPaypointID"
      field :id_batch, -> { Integer }, optional: true, nullable: false, api_name: "IdBatch"
      field :parent_org_name, -> { String }, optional: true, nullable: false, api_name: "ParentOrgName"
      field :paypoint_dba, -> { String }, optional: true, nullable: false, api_name: "PaypointDba"
      field :paypoint_id, -> { Integer }, optional: true, nullable: false, api_name: "PaypointId"
      field :paypoint_name, -> { String }, optional: true, nullable: false, api_name: "PaypointName"
      field :vcard_amount, -> { Integer }, optional: true, nullable: false, api_name: "VcardAmount"
      field :vcard_records, -> { Integer }, optional: true, nullable: false, api_name: "VcardRecords"
      field :vcard_status, -> { Integer }, optional: true, nullable: false, api_name: "VcardStatus"
      field :vcard_status_text, -> { String }, optional: true, nullable: false, api_name: "VcardStatusText"
      field :wire_amount, -> { Integer }, optional: true, nullable: false, api_name: "WireAmount"
      field :wire_records, -> { Integer }, optional: true, nullable: false, api_name: "WireRecords"
      field :wire_status, -> { Integer }, optional: true, nullable: false, api_name: "WireStatus"
      field :wire_status_text, -> { String }, optional: true, nullable: false, api_name: "WireStatusText"
    end
  end
end
