# frozen_string_literal: true

module Payabli
  module QueryTypes
    module Types
      class BatchDetailResponseRecord < Internal::Types::Model
        field :id, -> { Integer }, optional: false, nullable: false, api_name: "Id"
        field :method_, -> { String }, optional: false, nullable: false, api_name: "Method"
        field :wallet_type, -> { String }, optional: false, nullable: true, api_name: "WalletType"
        field :settled_amount, -> { Integer }, optional: false, nullable: false, api_name: "SettledAmount"
        field :type, -> { String }, optional: false, nullable: false, api_name: "Type"
        field :batch_number, -> { String }, optional: false, nullable: false, api_name: "BatchNumber"
        field :batch_amount, -> { Integer }, optional: false, nullable: false, api_name: "BatchAmount"
        field :payment_trans_id, -> { String }, optional: false, nullable: false, api_name: "PaymentTransId"
        field :payment_trans_status, -> { Integer }, optional: false, nullable: false, api_name: "PaymentTransStatus"
        field :schedule_reference, -> { Integer }, optional: false, nullable: false, api_name: "ScheduleReference"
        field :gateway_trans_id, -> { String }, optional: false, nullable: false, api_name: "GatewayTransId"
        field :order_id, -> { String }, optional: false, nullable: false, api_name: "OrderId"
        field :trans_method, -> { String }, optional: false, nullable: false, api_name: "TransMethod"
        field :payment_data, -> { Payabli::Types::QueryPaymentData }, optional: false, nullable: true, api_name: "PaymentData"
        field :net_amount, -> { Integer }, optional: false, nullable: false, api_name: "NetAmount"
        field :operation, -> { String }, optional: false, nullable: false, api_name: "Operation"
        field :category, -> { String }, optional: false, nullable: false, api_name: "Category"
        field :source, -> { String }, optional: false, nullable: true, api_name: "Source"
        field :status, -> { Integer }, optional: false, nullable: false, api_name: "Status"
        field :transaction_time, -> { String }, optional: false, nullable: false, api_name: "TransactionTime"
        field :customer, -> { Payabli::Types::QueryTransactionPayorData }, optional: false, nullable: true, api_name: "Customer"
        field :settlement_date, -> { String }, optional: false, nullable: false, api_name: "SettlementDate"
        field :payment_settlement_status, -> { Integer }, optional: false, nullable: false, api_name: "PaymentSettlementStatus"
        field :batch_status, -> { Integer }, optional: false, nullable: false, api_name: "BatchStatus"
        field :deposit_date, -> { String }, optional: false, nullable: false, api_name: "DepositDate"
        field :expected_deposit_date, -> { String }, optional: false, nullable: false, api_name: "ExpectedDepositDate"
        field :masked_account, -> { String }, optional: false, nullable: false, api_name: "MaskedAccount"
        field :created_at, -> { String }, optional: false, nullable: false, api_name: "CreatedAt"
        field :paypoint_legalname, -> { String }, optional: false, nullable: false, api_name: "PaypointLegalname"
        field :response_data, -> { Payabli::Types::QueryResponseData }, optional: false, nullable: true, api_name: "ResponseData"
        field :paypoint_dbaname, -> { String }, optional: false, nullable: false, api_name: "PaypointDbaname"
        field :parent_org_name, -> { String }, optional: false, nullable: false, api_name: "ParentOrgName"
        field :parent_org_id, -> { Integer }, optional: false, nullable: false, api_name: "ParentOrgId"
        field :paypoint_entryname, -> { String }, optional: false, nullable: false, api_name: "PaypointEntryname"
        field :device_id, -> { String }, optional: false, nullable: true, api_name: "DeviceId"
        field :retrieval_id, -> { Integer }, optional: false, nullable: false, api_name: "RetrievalId"
        field :chargeback_id, -> { Integer }, optional: false, nullable: false, api_name: "ChargebackId"
        field :ach_holder_type, -> { Payabli::Types::AchHolderType }, optional: false, nullable: false, api_name: "AchHolderType"
        field :ach_sec_code, -> { String }, optional: false, nullable: false, api_name: "AchSecCode"
        field :connector_name, -> { String }, optional: false, nullable: false, api_name: "ConnectorName"
        field :entrypage_id, -> { Integer }, optional: false, nullable: false, api_name: "EntrypageId"
        field :fee_amount, -> { Integer }, optional: false, nullable: false, api_name: "FeeAmount"
        field :org_id, -> { Integer }, optional: false, nullable: false, api_name: "OrgId"
        field :payor_id, -> { Integer }, optional: false, nullable: false, api_name: "PayorId"
        field :paypoint_id, -> { Integer }, optional: false, nullable: false, api_name: "PaypointId"
        field :pending_fee_amount, -> { Integer }, optional: false, nullable: false, api_name: "PendingFeeAmount"
        field :refund_id, -> { Integer }, optional: false, nullable: false, api_name: "RefundId"
        field :returned_id, -> { Integer }, optional: false, nullable: false, api_name: "ReturnedId"
        field :split_funding_instructions, -> { Internal::Types::Array[Payabli::Types::SplitFundingContent] }, optional: false, nullable: false, api_name: "splitFundingInstructions"
        field :total_amount, -> { Integer }, optional: false, nullable: false, api_name: "TotalAmount"
        field :cfee_transactions, -> { Internal::Types::Array[Payabli::Types::QueryCFeeTransaction] }, optional: false, nullable: false, api_name: "CfeeTransactions"
        field :invoice_data, -> { Payabli::Types::BillData }, optional: false, nullable: true, api_name: "invoiceData"
        field :transaction_events, -> { Internal::Types::Array[Payabli::Types::QueryTransactionEvents] }, optional: false, nullable: false, api_name: "TransactionEvents"
        field :external_paypoint_id, -> { String }, optional: false, nullable: false, api_name: "externalPaypointID"
        field :is_hold, -> { Integer }, optional: false, nullable: false, api_name: "isHold"
      end
    end
  end
end
