# frozen_string_literal: true

module Payabli
  module QueryTypes
    module Types
      # A record representing an outbound transfer detail.
      class TransferOutDetailRecord < Internal::Types::Model
        field :transfer_detail_id, -> { Integer }, optional: false, nullable: true, api_name: "transferDetailId"
        field :transfer_id, -> { Integer }, optional: false, nullable: true, api_name: "transferId"
        field :transaction_id, -> { String }, optional: false, nullable: true, api_name: "transactionId"
        field :id_out, -> { Integer }, optional: false, nullable: true, api_name: "IdOut"
        field :method_, -> { String }, optional: false, nullable: true, api_name: "method"
        field :type, -> { String }, optional: false, nullable: true
        field :category, -> { String }, optional: false, nullable: true
        field :gross_amount, -> { Integer }, optional: false, nullable: true, api_name: "grossAmount"
        field :returned_amount, -> { Integer }, optional: false, nullable: true, api_name: "returnedAmount"
        field :refund_amount, -> { Integer }, optional: false, nullable: true, api_name: "refundAmount"
        field :hold_amount, -> { Integer }, optional: false, nullable: true, api_name: "holdAmount"
        field :released_amount, -> { Integer }, optional: false, nullable: true, api_name: "releasedAmount"
        field :billing_fees_amount, -> { Integer }, optional: false, nullable: true, api_name: "billingFeesAmount"
        field :adjustments_amount, -> { Integer }, optional: false, nullable: true, api_name: "adjustmentsAmount"
        field :net_transfer_amount, -> { Integer }, optional: false, nullable: true, api_name: "netTransferAmount"
        field :billing_fees_details, -> { Internal::Types::Array[Payabli::Types::BillingFeeDetail] }, optional: false, nullable: true, api_name: "billingFeesDetails"
        field :created_at, -> { String }, optional: false, nullable: true, api_name: "CreatedAt"
        field :comments, -> { String }, optional: false, nullable: true, api_name: "Comments"
        field :vendor, -> { Payabli::QueryTypes::Types::TransferOutDetailVendor }, optional: false, nullable: true, api_name: "Vendor"
        field :paypoint_dbaname, -> { String }, optional: false, nullable: true, api_name: "PaypointDbaname"
        field :paypoint_legalname, -> { String }, optional: false, nullable: true, api_name: "PaypointLegalname"
        field :paypoint_id, -> { Integer }, optional: false, nullable: true, api_name: "PaypointId"
        field :status, -> { Integer }, optional: false, nullable: true, api_name: "Status"
        field :payment_id, -> { String }, optional: false, nullable: true, api_name: "PaymentId"
        field :trans_id, -> { String }, optional: false, nullable: true, api_name: "TransId"
        field :trans_status, -> { Integer }, optional: false, nullable: true, api_name: "TransStatus"
        field :trans_status_detail, -> { String }, optional: false, nullable: true, api_name: "TransStatusDetail"
        field :trans_status_name, -> { String }, optional: false, nullable: true, api_name: "TransStatusName"
        field :trans_status_category, -> { String }, optional: false, nullable: true, api_name: "TransStatusCategory"
        field :last_updated, -> { String }, optional: false, nullable: true, api_name: "LastUpdated"
        field :total_amount, -> { Integer }, optional: false, nullable: true, api_name: "TotalAmount"
        field :net_amount, -> { Integer }, optional: false, nullable: true, api_name: "NetAmount"
        field :fee_amount, -> { Integer }, optional: false, nullable: true, api_name: "FeeAmount"
        field :source, -> { String }, optional: false, nullable: true, api_name: "Source"
        field :parent_org_name, -> { String }, optional: false, nullable: true, api_name: "ParentOrgName"
        field :parent_org_id, -> { Integer }, optional: false, nullable: true, api_name: "ParentOrgId"
        field :batch_number, -> { String }, optional: false, nullable: true, api_name: "BatchNumber"
        field :payment_status, -> { String }, optional: false, nullable: true, api_name: "PaymentStatus"
        field :payment_method, -> { String }, optional: false, nullable: true, api_name: "PaymentMethod"
        field :card_token, -> { String }, optional: false, nullable: true, api_name: "CardToken"
        field :check_number, -> { String }, optional: false, nullable: true, api_name: "CheckNumber"
        field :check_data, -> { Payabli::QueryTypes::Types::TransferOutDetailCheckData }, optional: false, nullable: true, api_name: "CheckData"
        field :payment_data, -> { Payabli::QueryTypes::Types::TransferOutDetailPaymentData }, optional: false, nullable: true, api_name: "PaymentData"
        field :bills, -> { Internal::Types::Array[Payabli::QueryTypes::Types::TransferOutDetailBill] }, optional: false, nullable: true, api_name: "Bills"
        field :events, -> { Internal::Types::Array[Payabli::QueryTypes::Types::TransferOutDetailEvent] }, optional: false, nullable: true, api_name: "Events"
        field :external_paypoint_id, -> { String }, optional: false, nullable: true, api_name: "externalPaypointID"
        field :entry_name, -> { String }, optional: false, nullable: true, api_name: "EntryName"
        field :gateway, -> { String }, optional: false, nullable: true, api_name: "Gateway"
        field :batch_id, -> { Integer }, optional: false, nullable: true, api_name: "BatchId"
        field :has_vcard_transactions, -> { Internal::Types::Boolean }, optional: false, nullable: true, api_name: "HasVcardTransactions"
        field :is_same_day_ach, -> { Internal::Types::Boolean }, optional: false, nullable: true, api_name: "IsSameDayACH"
        field :schedule_id, -> { Integer }, optional: false, nullable: true, api_name: "ScheduleId"
        field :settlement_status, -> { String }, optional: false, nullable: true, api_name: "SettlementStatus"
        field :settlement_status_name, -> { String }, optional: false, nullable: true, api_name: "SettlementStatusName"
        field :settlement_date, -> { String }, optional: false, nullable: true, api_name: "SettlementDate"
        field :risk_flagged, -> { Internal::Types::Boolean }, optional: false, nullable: true, api_name: "RiskFlagged"
        field :risk_flagged_on, -> { String }, optional: false, nullable: true, api_name: "RiskFlaggedOn"
        field :risk_status, -> { String }, optional: false, nullable: true, api_name: "RiskStatus"
        field :risk_reason, -> { String }, optional: false, nullable: true, api_name: "RiskReason"
        field :risk_action, -> { String }, optional: false, nullable: true, api_name: "RiskAction"
        field :risk_action_code, -> { Integer }, optional: false, nullable: true, api_name: "RiskActionCode"
        field :payout_program, -> { String }, optional: false, nullable: true, api_name: "PayoutProgram"
        field :ach_trace_number, -> { String }, optional: false, nullable: true, api_name: "AchTraceNumber"
      end
    end
  end
end
