# frozen_string_literal: true

module Payabli
  module Types
    class QueryEntrypointResponseRecordsItem < Internal::Types::Model
      field :average_monthly_volume, -> { Integer }, optional: true, nullable: false, api_name: "AverageMonthlyVolume"
      field :average_ticket_amount, -> { Integer }, optional: true, nullable: false, api_name: "AverageTicketAmount"
      field :b_address_1, -> { String }, optional: true, nullable: false, api_name: "BAddress1"
      field :b_address_2, -> { String }, optional: true, nullable: false, api_name: "BAddress2"
      field :bank_data, -> { Internal::Types::Array[Payabli::Types::Bank] }, optional: true, nullable: false, api_name: "BankData"
      field :b_city, -> { String }, optional: true, nullable: false, api_name: "BCity"
      field :b_country, -> { String }, optional: true, nullable: false, api_name: "BCountry"
      field :b_fax, -> { String }, optional: true, nullable: false, api_name: "BFax"
      field :bin_person, -> { Integer }, optional: true, nullable: false, api_name: "BinPerson"
      field :bin_phone, -> { Integer }, optional: true, nullable: false, api_name: "BinPhone"
      field :bin_web, -> { Integer }, optional: true, nullable: false, api_name: "BinWeb"
      field :boarding_id, -> { Integer }, optional: true, nullable: false, api_name: "BoardingId"
      field :b_phone, -> { String }, optional: true, nullable: false, api_name: "BPhone"
      field :b_startdate, -> { String }, optional: true, nullable: false, api_name: "BStartdate"
      field :b_state, -> { String }, optional: true, nullable: false, api_name: "BState"
      field :b_summary, -> { String }, optional: true, nullable: false, api_name: "BSummary"
      field :b_time_zone, -> { Integer }, optional: true, nullable: false, api_name: "BTimeZone"
      field :b_zip, -> { String }, optional: true, nullable: false, api_name: "BZip"
      field :contact_data, -> { Internal::Types::Array[Payabli::Types::Contacts] }, optional: true, nullable: false, api_name: "ContactData"
      field :created_at, -> { String }, optional: true, nullable: false, api_name: "CreatedAt"
      field :dba_name, -> { String }, optional: true, nullable: false, api_name: "DbaName"
      field :documents_ref, -> { String }, optional: true, nullable: false, api_name: "DocumentsRef"
      field :ein, -> { String }, optional: true, nullable: false, api_name: "Ein"
      field :entry_points, -> { Internal::Types::Array[Payabli::Types::PaypointEntryConfig] }, optional: true, nullable: false, api_name: "EntryPoints"
      field :external_paypoint_id, -> { String }, optional: true, nullable: false, api_name: "externalPaypointID"
      field :external_processor_information, -> { String }, optional: true, nullable: false, api_name: "ExternalProcessorInformation"
      field :high_ticket_amount, -> { Integer }, optional: true, nullable: false, api_name: "HighTicketAmount"
      field :id_paypoint, -> { Integer }, optional: true, nullable: false, api_name: "IdPaypoint"
      field :last_modified, -> { String }, optional: true, nullable: false, api_name: "LastModified"
      field :legal_name, -> { String }, optional: true, nullable: false, api_name: "LegalName"
      field :license, -> { String }, optional: true, nullable: false, api_name: "License"
      field :license_state, -> { String }, optional: true, nullable: false, api_name: "LicenseState"
      field :m_address_1, -> { String }, optional: true, nullable: false, api_name: "MAddress1"
      field :m_address_2, -> { String }, optional: true, nullable: false, api_name: "MAddress2"
      field :mccid, -> { String }, optional: true, nullable: false, api_name: "Mccid"
      field :m_city, -> { String }, optional: true, nullable: false, api_name: "MCity"
      field :m_country, -> { String }, optional: true, nullable: false, api_name: "MCountry"
      field :m_state, -> { String }, optional: true, nullable: false, api_name: "MState"
      field :m_zip, -> { String }, optional: true, nullable: false, api_name: "MZip"
      field :org_id, -> { Integer }, optional: true, nullable: false, api_name: "OrgId"
      field :org_parent_name, -> { String }, optional: true, nullable: false, api_name: "OrgParentName"
      field :owner_data, -> { Internal::Types::Array[Payabli::Types::Owners] }, optional: true, nullable: false, api_name: "OwnerData"
      field :own_type, -> { Payabli::Types::OwnType }, optional: true, nullable: false, api_name: "OwnType"
      field :paypoint_status, -> { Integer }, optional: true, nullable: false, api_name: "PaypointStatus"
      field :sales_code, -> { String }, optional: true, nullable: false, api_name: "SalesCode"
      field :service_data, -> { Payabli::Types::Services }, optional: true, nullable: false, api_name: "ServiceData"
      field :summary, -> { Payabli::Types::PaypointSummary }, optional: true, nullable: false
      field :taxfillname, -> { String }, optional: true, nullable: false, api_name: "Taxfillname"
      field :template_id, -> { Integer }, optional: true, nullable: false, api_name: "TemplateId"
      field :website_address, -> { String }, optional: true, nullable: false, api_name: "WebsiteAddress"
      field :whencharged, -> { Payabli::Types::Whencharged }, optional: true, nullable: false, api_name: "Whencharged"
      field :whendelivered, -> { Payabli::Types::Whendelivered }, optional: true, nullable: false, api_name: "Whendelivered"
      field :whenprovided, -> { Payabli::Types::Whenprovided }, optional: true, nullable: false, api_name: "Whenprovided"
      field :whenrefund, -> { Payabli::Types::Whenrefunded }, optional: true, nullable: false, api_name: "Whenrefund"
    end
  end
end
